### ISSUE TITLE
出社予定を取り消すことができない。

### ISSUE THREAD

**Issue by acannie** [akichil-fj/shusshare#22]
出社予定の `取り消し` ボタンをクリックすると、`失敗：日付のフォーマットを確認してください。` と出て取り消しに失敗するようです。

![image](https://user-images.githubusercontent.com/48375338/178272846-83462e39-60d1-4087-9449-931fee4462b0.png)

**Comment by akichil-fj** [comment]
バグ報告ありがとう！多分直ったと思います
