### ISSUE TITLE
環境変数からdb接続に必要な情報を取得したい

### ISSUE THREAD

**Issue by l1lhu1hu1** [akichil-fj/shusshare#25]
開発のためにapplication.ymlを編集する場合、誤ってcommitにusernameやpassword等のdb接続に必要な情報が紛れ込んでしまうため

**Comment by akichil-fj** [comment]
<img width="282" alt="image" src="https://user-images.githubusercontent.com/49609538/179780057-55b85921-1630-420a-b2d7-2c140166823a.png">
現状自分は`application-xxx.yml`(gitの対象外)を作ってそっちにusernameとかpasswordとか書いて、実行時にプロファイル指定して、設定読み込んでる

この管理方法は微妙？(結局git add -Aとかするとまずい)

**Comment by l1lhu1hu1** [comment]
application-staging.ymlとかapplication-production.ymlはいいと思うんだけど、開発用のは間違ってpassword等の情報が混じりっちゃいそうだから、環境変数を読み込むのがいい気がする！毎回application-user名.ymlをcheckoutする手間も削減できるしさ！

一応調べているから、もしやるのであれば自分の方ですぐにPR送れると思う！

**Comment by akichil-fj** [comment]
なるほど確かに

ちなみに本番環境では環境変数で運用してるんやけど、何かソース変更する必要ありそう？
```
SPRING_DATASOURCE_USERNAME="xxxxx"
SPRING_DATASOURCE_PASSWORD="xxxxx"
```
とかを環境変数に入れておけば多分Springがよしなにやってくれてる

**Comment by l1lhu1hu1** [comment]
それ知らなかった。それなら新たに設定不要だな〜

代わりに前に作ったPRのreadmeにSPRING_DATASOURCE_USERNAMEとSPRING_DATASOURCE_PASSWORDの説明も追加しておく〜

このissueはcloseしておくね
